### PR TITLE
update most deps

### PR DESCRIPTION
**Pull request by KenanY**
This patch updates all deps to their latest versions (except `multer`, which will require a bit more work).

I tested this a bit locally and everything appears to be working fine but let me know if you find any issues.

Closes https://github.com/ILiedAboutCake/OverRustle-API/issues/23

### CODE REVIEW

**Comment by hayksaakian** [comment]
does redis have any breaking changes that affect us? other than that seems like it should work

**Comment by KenanY** [comment]
Seems like a lot has happened in the last couple of years since `redis@0.12.1` so it would be tough to say. Seems like we connect to the redis server just fine, but I don't know what more to look for.

**Comment by KenanY** [comment]
As disastrous as it may be, I am starting to think (given the lack of any apparent failures in local testing) we should just deploy to live and see what happens. It would be easy to rollback if anything goes wrong, and many of the users are already sort of "used to" the recent overrustle downtime anyways. I know this approach may be a bit unorthodox (and also that it puts more work on others) but I'm at a loss as to what else I can do here :)

**Comment by ILiedAboutCake** [comment]
Tried this last night in production after pushing nodejs and the kernel to the latest version. Even ignoring the multer update the API output became a bunch unreadable nonsense

**Comment by KenanY** [comment]
Oh, rip. I gotta try simulating more than just one stream perhaps.

**Comment by KenanY** [comment]
In the process of rewriting everything anyways so this won't be needed.

**Pull request closed without merging**
